import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  textInput: {
    borderColor: 'pink',
    borderWidth: 2,
    width: 200,
    textAlign: 'center',
  },
  touchableHightlight: {
    borderColor: 'black',
    borderWidth: 2,
  },
  button: {
    marginTop: 30,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 20,
    paddingRight: 20,
    borderColor: 'white',
    borderWidth: 2,
    backgroundColor: 'pink',
  },
  buttonText: {
    color: 'white',
  },
  modalTitleText: {
    fontWeight: 'bold',
    fontSize: 24,
    textAlign: 'center',
    margin: 50,
  },
  container: {
    marginTop: 50,
    height: 30,
    flexDirection: 'row',
    alignItems: 'space-between',
  },
  pink: {
    margin: 5,
    flex: 1,
    height: 20,
    width: 20,
    backgroundColor: '#EB9694',
  },
  orange: {
    margin: 5,
    flex: 1,
    height: 20,
    width: 20,
    backgroundColor: '#FAD0C3',
  },
  yellow: {
    margin: 5,
    flex: 1,
    height: 20,
    width: 20,
    backgroundColor: '#FEF3BD',
  },
  green: {
    margin: 5,
    flex: 1,
    height: 20,
    width: 20,
    backgroundColor: '#C1E1C5',
  },
  bluegreen: {
    margin: 5,
    flex: 1,
    height: 20,
    width: 20,
    backgroundColor: '#BEDADC',
  },
  blue: {
    margin: 5,
    flex: 1,
    height: 20,
    width: 20,
    backgroundColor: '#C4DEF6',
  },
  darkblue: {
    margin: 5,
    flex: 1,
    height: 20,
    width: 20,
    backgroundColor: '#BED3F3',
  },
  purple: {
    margin: 5,
    flex: 1,
    height: 20,
    width: 20,
    backgroundColor: '#D4C4FB',
  },
});
