import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  textInput: {
    borderColor: 'grey',
    borderWidth: 1,
    width: 200,
    textAlign: 'center',
    marginBottom: 15,
  },
  touchableHightlight: {
    borderColor: 'black',
    borderWidth: 1,
  },
  button: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 4,
    paddingRight: 4,
    marginBottom: 25,
    borderColor: 'white',
    borderWidth: 2,
    backgroundColor: 'green',
    borderRadius: 10,
  },
  buttonText: {
    fontWeight: 'bold',
    color: 'white',
  },
  modalTitleText: {
    fontWeight: 'bold',
    fontSize: 20,
    textAlign: 'center',
    margin: 30,
  },
  container: {
    margin: 10,
    height: 30,
    flexDirection: 'row',
    alignItems: 'center',
  },
  pink: {
    margin: 5,
    flex: 1,
    height: 20,
    width: 20,
    backgroundColor: '#EB9694',
  },
  orange: {
    margin: 5,
    flex: 1,
    height: 20,
    width: 20,
    backgroundColor: '#FAD0C3',
  },
  yellow: {
    margin: 5,
    flex: 1,
    height: 20,
    width: 20,
    backgroundColor: '#FEF3BD',
  },
  green: {
    margin: 5,
    flex: 1,
    height: 20,
    width: 20,
    backgroundColor: '#C1E1C5',
  },
  bluegreen: {
    margin: 5,
    flex: 1,
    height: 20,
    width: 20,
    backgroundColor: '#BEDADC',
  },
  blue: {
    margin: 5,
    flex: 1,
    height: 20,
    width: 20,
    backgroundColor: '#C4DEF6',
  },
  darkblue: {
    margin: 5,
    flex: 1,
    height: 20,
    width: 20,
    backgroundColor: '#BED3F3',
  },
  purple: {
    margin: 5,
    flex: 1,
    height: 20,
    width: 20,
    backgroundColor: '#D4C4FB',
  },
});
